name: .NET Core

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        source-url: https://nuget.pkg.github.com/fsclient/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Nuget Pack
      run: dotnet pack ./LiteDB/LiteDB.csproj --include-source --include-symbols --configuration Release -o ./artifacts

    - name: Publish
      run: dotnet nuget push ./artifacts/LiteDB*.nupkg

    - name: Nuget Pack
      run: dotnet pack ./LiteDB.Async/LiteDB.Async.csproj --include-source --include-symbols --configuration Release -o ./artifacts

    - name: Publish
      run: dotnet nuget push ./artifacts/LiteDB.Async*.nupkg
